ETAPA 1 - MODELAGEM BASICA

CLIENTE


NOME 
CPF 
EMAIL 
TELEFONE 
ENDEREÇO
SEXO

ETAPA 2 - MODELAGEM LOGICA

CLIENTE


NOME - CARACTER(30)
CPF - CARACTER(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(10)
ENDEREÇO - CARACTER(100)
SEXO - CARACTER(1)

ETAPA 3 - MODELAGEM CONCEITUAL

CREATE TABLE ( 
    NOME VARCHAR(30),
    CPF VARCHAR(11),
    EMAIL VARCHAR(30),
    TELEFONE VARCHAR(30),
    EMDEREÇO VARCHAR(30),
    SEXO CHAR(1)

)
SHOW TABLES,

/*SINTAXE BASICA DE INSERÇÃO - INSERT TABELA*/

INSERT INTO CLIENTE VALUES("Bruno","124344344","alipiotanana@hotmail.com",
"19988377434","rua zoraide correa alves","M");

INSERT INTO CLIENTE(NOME,CPF,EMAIL,TELEFONE,ENDERECO,SEXO)
VALUES("Bruno","124344344","alipiotanana@hotmail.com",
"19988377434","rua zoraide correa alves","M")